apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openreplay-prod-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rjshrjndrn/eso-test.git
    targetRevision: main
    path: instances/openreplay-prod/apps
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
