apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: or-secrets-cluster
spec:
  externalSecretName: or-secrets-external

  # Create ExternalSecrets in app and db namespaces
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - app
            - db

  refreshTime: 1m

  externalSecretSpec:
    refreshInterval: 5m
    secretStoreRef:
      name: azure-keyvault
      kind: ClusterSecretStore
    target:
      name: or-secrets
      creationPolicy: Owner
    data:
      - secretKey: access-key
        remoteRef:
          key: access-key
      - secretKey: secret-key
        remoteRef:
          key: secret-key
      - secretKey: assist-jwt-secret
        remoteRef:
          key: assist-jwt-secret
      - secretKey: assist-key
        remoteRef:
          key: assist-key
      - secretKey: clickhouse-password
        remoteRef:
          key: clickhouse-password
      - secretKey: jwt-refresh-secret
        remoteRef:
          key: jwt-refresh-secret
      - secretKey: jwt-secret
        remoteRef:
          key: jwt-secret
      - secretKey: jwt-spot-refresh-secret
        remoteRef:
          key: jwt-spot-refresh-secret
      - secretKey: jwt-spot-secret
        remoteRef:
          key: jwt-spot-secret
      - secretKey: license-key
        remoteRef:
          key: license-key
      - secretKey: postgresql-password
        remoteRef:
          key: postgresql-password
      - secretKey: token-secret
        remoteRef:
          key: token-secret
      - secretKey: azure-account-key
        remoteRef:
          key: azure-account-key
